services:
  postgres:
    image: postgres:16
    container_name: mafia_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mafia
      POSTGRES_PASSWORD: mafia
      POSTGRES_DB: mafia
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: mafia_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:


